baseurl = "https://fernandosimoes.com"
title = "Fernando Simões"
theme = "bg"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 50

# language
defaultContentLanguage = 'en'

[menu]
  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "about/"
        weight = 2
  [[menu.main]]
        identifier = "posts"
        name = "Blog"
        url = "posts/"
        weight = 1

[taxonomies]
  tag = "tags"

# Footer
  [[menu.footer]]
        name = "github"
        url = "https://github.com/frnsimoes"
        weight = 1 
  [[menu.footer]]
        name = "linkedin"
        url = "https://linkedin.com/in/frnsimoes"
        weight = 1 

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"
